version: 2
jobs:
  MAKE:
    docker:
      - image: martinfger/iot_devel:1.0
    steps:
      - checkout
      - run:
          name: "System"
          command: |
            apt update
            apt install -y git
            git pull
      - run:
          name: "Build"
          command: |
            make

workflows:
    version: 2
    run_ci:
        jobs:
            - MAKE
